services:
  - type: web
    name: cyberztalk-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://palegreen-llama-259442.hostingersite.com
      - key: SOCKET_IO_CORS_ORIGIN
        value: https://palegreen-llama-259442.hostingersite.com
